### ISSUE TITLE
Every update corrupts my data. Any way around this?

### ISSUE THREAD

**Issue by fwyrl** [asdfjackal/warframe-checklist#22]
Every time content is added to the web page, my data is altered. For instance, after this most recent update, my Warframe catagory now has Mesa un-obtained and un-leveled, instead of Loki Prime. In addition, though I have 5/5 researched, Banshee, Nezha, Volt, and Wukong were not marked as such. Marking these brought me to 9/5 researched.

This issue occurred to: Frames, Primaries, Secondaries, Melees, and Companions this update.

Is there any way to avoid this? Maybe store the check boxes by string (say, "bansheeResearched"), as opposed to ID? (I don't know much about how you're storing the information, so this could totally be not do-able)

If this isn't possible, could we get a "check all obtainable" option? Some way to mark that all currently obtainable items are obtained, MR 30, and (if applicable), researched? I'd say mark all, but this would probably be more useful, since most people using this won't have Sigma & Octanis, Skana Prime, Excal Prime, etc.

**Comment by asdfjackal** [comment]
Sorry for the late response, I have been getting over the flu for the past week and a half.

It is difficult to diagnose this kind of issue without a little more information.
The next time you run into this issue, please go into your developer console (F12 on most browsers) and enter the following string: 
`localStorage.getItem("warframe-item-checklist");`
Paste the results in a comment on this issue. Additionally, if you could provide the following info please do so:
- Operating System
- Browser (and version number)
- Screenshots if possible

As for the "check all obtainable" option, that is a very manageable feature and I will add it with the next content update.

**Comment by fwyrl** [comment]
I'm on Windows 7, with the latest Firefox. I'll keep an eye on the list and see if the issue occurs with the next content patch, as I haven't seen anything else cause weird data issues.

Is there any way to get the whole string? I only get a seriously truncated output right now, and google is failing me on how to turn off Firefox's web dev console truncation.

**Comment by RylaiSlyfe** [comment]
I do have the same problem with my data corrupting and I also only get the first part printed like fwyrl.

`"{"version":"2018.03.07.14.18","lists":[{"title":"Frames","list":[{"title":"Ash","acquired":true,"rankThirty":true,"researched":false},{"title":"Ash Prime","acquired":true,"rankThirty":true,"researched":false},{"title":"Atlas","acquired":true,"rankThirty":true,"researched":false},{"title":"Banshee","acquired":true,"rankThirty":true,"researched":true},{"title":"Banshee Prime","acquired":true,"rankThirty":true,"researched":false},{"title":"Chroma","acquired":true,"rankThirty":true,"researched":false},{"title":"Ember","acquired":true,"rankThirty":true,"researched":false},{"title":"Ember Prime","acquired":true,"rankThirty":true,"researched":false},{"title":"Equinox","acquired":true,"rankThirty":true,"researched":false},{"title":"Excalibur","acquired":true,"rankThirty":true,"researched":false},{"title":"Excalibur Prime","acquired":true,"rankThirty":true,"researched":false},{"title":"Frost","acquired":true,"rankThirty":true,"researched":false},{"title":"Frost Prime","acquired":true,"rankThirt"[…]`

This is my print. I use Windows 10, latest Firefox(50.0).

Now to further explain what is happening.... In the following picture we see my personal List corrupted. Things like the Sobek, Tigris Prime, Corinth, Azima should defenitely  be marked as Rank 30 with me since I main these weapons since I started the game.
![2018-03-20 09_54_29-](https://user-images.githubusercontent.com/16038306/37644811-d8959380-2c1c-11e8-9def-dde03307cbbe.png)

What I also noticed is, that the data I marked for experimenting for this exact issue, was not touched. I put all on true and it still is. So I think it does not just randomly select and deselect some items but rather switches them around since the number of aquired items did not seem to have changed.
![2018-03-20 09_54_41-](https://user-images.githubusercontent.com/16038306/37644805-d523ca78-2c1c-11e8-8b0b-7fa3bf25583c.png)

**Comment by asdfjackal** [comment]
It is possible that this is an issue with Firefox. At the very least I would update your browser since Firefox 50 was last updated November of 2016, although fwyrl reported using the latest version of the browser so it is likely not an issue with version. 

I suspect that this is some quirk of the Javascript engine that Firefox uses, so I will load it up on my development machine and see if I can track down the issue. At the very least I will add the "check all obtainable" feature mentioned earlier in this thread that I missed in the last content update.

**Comment by asdfjackal** [comment]
I tested on both my local machine and again when I deployed #25 by changing every value in the saved data to true and simulating (or in the case of the deployment actually causing) changes to both the empty list and the list data. The result is shown below (this is the end result of the deployment of #25).

![result](https://puu.sh/zM1iQ/1fe9aeaafd.png)

**Comment by fwyrl** [comment]
![image](https://user-images.githubusercontent.com/13026693/38069269-7579b592-32e3-11e8-8e45-2c31eb6f9e72.png)

**Comment by fwyrl** [comment]
The most recent update certainly moved the check boxes, though I think you're right that it's just moving them - I still have the same number mastered.

For primaries, for instance, had Cernos and Corinth unchecked, instead of the Braton Vandal and Zenith (iirc - not 100% sure that's what the second one was)
Secondaries have MK1-Furis and Marelok unchecked, instead of Lato Prime and Lato Vandal
Melee had Vaykor Sydon and Zenistar unchecked, instead of the Sigma & Octanis and Skana Prime

Interestingly, Zephyr Prime, Tiberon Prime and Kronen Prime were unchecked, as they should have been.

How do I get it to output a non-truncated dev output for ya?

Attached image showing (probably related) issue with researched boxes moving around. These were all checked (note that is still says 30/30, despite having many boxes unchecked)
![image](https://user-images.githubusercontent.com/13026693/38069662-802e6ff8-32e5-11e8-9f75-406c3700aa7a.png)
